version: '2'

services:

  vtiger:
    build: ${version}
    environment:
      - VT_DEBUG=false
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./:/app
      - ./vtiger:/var/lib/vtiger
    links:
      - mysql
      - adminer

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8081:8080
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

volumes:
  mysql:
